martinohansen/ynabber

- README.md
- cmd/ynabber/main.go
- config.go
- go.mod
- go.sum
- reader/nordigen/auth.go
- reader/nordigen/auth_test.go
- reader/nordigen/nordigen.go
- reader/nordigen/nordigen_test.go
- writer/ynab/ynab.go
- ynabber.go
Instead of loading config values from the environment at time of need
this moves the config into a struct that gets loaded during startup.
This makes documenting and parsing the config easier and more readable.
> feat(config): move all config values into struct

- writer/ynab/ynab.go
Show more debugging output when debugging is on namely the json sent to YNAB and what is the actual response.
This is especially useful in error situations.
The 'Bad request' response is not enough as there is important information in the response body as well.
Also seeing the sent request is very helpful. 
These modification at least helped me to see what is the problem with one particular account.
> Show json sent to YNAB and response when debugging is on

- cmd/ynabber/main.go
- config.go
This allows periodic runs from, for example, crontab. Also useful for testing where you rarely want it to run in loop.
Besides previously zero meant basically busy loop which is not desirable anyway.
> Make interval=0 mean run only once

- reader/nordigen/nordigen.go
Continue to next account on Nordigens list instead of bypassing rest
> Do not bypass accounts coming after an unfound account in accountmap

- config.go
- reader/nordigen/nordigen.go
My mistake for the earlier datafile option - it should have been relative from the start.
This PR preserves functionality as it was for absolute paths(which was in practice a requirement before) but is more logical if the datadir is set.
> Use relative path for datafile by default

- cmd/ynabber/main.go
- config.go
- writer/ynab/ynab.go
A minor additional feature. I prefer getting the transactions cleared because, by definition, cleared=cleared by bank, which applies to all transactions ynabber imports. 
Just to make sure they won't be approved automatically, though, (payee and/or memo may still be incorrect or even require splitting), set the approved status to false.
I could not find the API defaults from YNAB API documentation although I think approved is false by default.
> Add possibility to set the cleared status of imported transactions

- reader/nordigen/auth.go
- reader/nordigen/nordigen.go
The error status seems to be used to intermediate (e.g. 503) errors on the Nordigen backend. Instead of recreating the requisition in that case we just need to fail and let whatever is running the process handle it.
Fixes #40
> fix(nordigen): do not recreate req on error

- config.go
- reader/nordigen/auth.go
- reader/nordigen/nordigen.go
In order to make the fulfillment of requisitions easier, users are now able to configure a script that will be called when a new requisition has been created. This idea can expand to create a second requisition once the current requisition expires soon.
This idea was dicussed in https://github.com/martinohansen/ynabber/issues/54 - this PR serves as a basis for discussion.
The config file supports a new property called `NOTIFICATION_SCRIPT`. This script is executed every time a new requisiton URL is created. The script receives the requisition link as a parameter. 
Here's an example to post it to logsnag:
`ynabber.env`:
```.env filename="ynabber.env"
NOTIFICATION_SCRIPT=/Users/myuser/post-logsnag,sh
```
`post-logsnag,sh`:
```sh filename="post-logsnag,sh"
#!/bin/bash
reqURL=$1
curl …
```
> Added Basic Shell Notifications

- cmd/ynabber/main.go
- config.go
- reader/nordigen/auth.go
- reader/nordigen/auth_test.go
- reader/nordigen/hooks/example.sh
- reader/nordigen/nordigen.go
Rework the requisition fulfillment to be under the Reader struct and simplify the file handling.
Move the requisition hook to the Nordigen config struct and make it more generic so i can be used to handle arbitrary events tied to the requisition and its status.
BREAKING CHANGE: Remove NORDIGEN_DATAFILE in favor of the YNABBER_DATADIR option. This will require recreating the requisition.
> feat(nordigen)!: add requisition hook

- config.go
- reader/nordigen/mapper.go
Bring back support for the user to change transaction ID. Lets give the users the power to change stuff while we still attempt to support all banks with specific mappers out of the box.
Fixes #64
> fix(nordigen): bring back transaction ID option

- .gitignore
- config.go
- reader/nordigen/auth.go
This commit brings back the ability to override the requisition file used by Nordigen. Allowing the user to have multiple req. files inside the same data directory.
Fixes #69
> fix(Nordigen): bring back file override

- writer/ynab/ynab.go
- writer/ynab/ynab_test.go
- ynabber.go
Fix error 400 from YNAB API when a transaction date is in the future or more than 5 years ago.
Fixes #73
> fix(YNAB): date must not be in the future

- cmd/ynabber/main.go
- config.go
- reader/nordigen/nordigen.go
- writer/ynab/ynab.go
- writer/ynab/ynab_test.go
Add structured logging for greater viability into the transaction
mappings. Also use a decoder for the YNAB cleared status, simply done to
have less log statements.
---
**Stack**:
- #81
- #80
- #79 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> refactor: use slog for logging

- cmd/ynabber/main.go
- reader/nordigen/nordigen.go
- writer/ynab/ynab.go
- writer/ynab/ynab_test.go
commit-id:4d94901c
---
**Stack**:
- #87
- #86 ⬅
- #85
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> test: validate delay config

- reader/nordigen/nordigen.go
Crude way to fail gracefully when the rate limit is exceeded.
Ref: #76
> fix(nordigen): skip account on rate limit exceeded

- reader/nordigen/mapper.go
- reader/nordigen/nordigen.go
- reader/nordigen/nordigen_test.go
Nordea never sleeps, this is a fix for a duplicate transactions which is
caused by Nordea showing the same transaction twice with different
transaction IDs.
BREAKING CHANGE: Nordea users will have new import IDs generated which
causes duplicate transactions. To fix this set the YNAB_FROM_DATE value
to the day you start using this version.
> fix(nordigen): nordea duplicate transactions

- go.mod
- go.sum
- reader/nordigen/mapper.go
- reader/nordigen/mapper_test.go
- reader/nordigen/nordigen.go
- reader/nordigen/nordigen_test.go
- ynabber.go
- ynabber_test.go
Refactor toYnabber into a single function, the nil check was on a layer
too high before. Remove that pit fall by just having one function for
the translation.
Move the strip function into the mapper, it was a leftover from when the
config value was defined on the YNAB side. We want to mangle data closet
to the read point.
> fix(nordigen): nil pointer

- cmd/ynabber/main.go
- ynabber.go
Use channels to batch transactions and fan out to writers. This is
prep work for allowing multiple "pipelines" of readers and writers and
potentially multiple instances of Ynabber running concurrently.
> refactor(ynabber): channels for fan out to writers

- .github/workflows/go.yml
Potential fix for [https://github.com/martinohansen/ynabber/security/code-scanning/1](https://github.com/martinohansen/ynabber/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will specify `contents: read`, which is sufficient for the current workflow since it only checks out the repository and runs build and test commands. This change ensures that the workflow does not have unnecessary write permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Workflow does not contain permissions

- cmd/ynabber/main.go
- errors.go
- errors_test.go
- reader/nordigen/nordigen.go
- writer/json/json.go
- writer/ynab/ynab.go
- ynabber.go
If we get an error in the reader, close it and let the program crash.  Handle retires if rate limited as long as we are not running in on-shot  mode aka interval=0.
If a writer fails or we have multiple readers and not all of them  fail, the program could hang in a suboptimal state. We need to solve  that eventually.
Close: #117
Fix: #110
> fix: not crashing on error

- reader/nordigen/auth.go
- reader/nordigen/config.go
Log the output from the hook using the logger and return error instead 
of int for more idomatic go.
> fix(nordigen): use logger for hook output
